# Generated by Django 3.2.12 on 2023-10-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_order_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='order',
            name='receipt',
            field=models.FileField(null=True, upload_to='orders/receipts'),
        ),
    ]
