# Generated by Django 3.2.12 on 2023-10-18 11:27

from django.db import migrations, models
import django.db.models.deletion
import info.models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_product_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=info.models.product_images_directory_path)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='info.product')),
            ],
        ),
    ]
